GET http://localhost:3000/users

###

GET http://localhost:3000/users?limit=1

###

GET http://localhost:3000/users/b18940c0-bee

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "zzssdng@ss", 
  "firstName": "손",
  "lastName": "감동",
  "address": "보우하트"
}

###

PATCH http://localhost:3000/users/aeb7cf4c-7af2

{
  "address": "z "
}

###

DELETE http://localhost:3000/users/b8f11e76-0a9e-4b3f-bccf-8d9b4